name: chatchat
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.5.6+1

environment:
  sdk: ^3.5.1

dependencies:
  awesome_dialog: ^3.2.1
  cached_network_image: ^3.4.1
  chat_bubbles:
    path: packages/chat_bubbles/
  cloud_firestore: ^5.6.6
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_link_previewer:
    path: packages/flutter_link_previewer/
  flutter_local_notifications: ^19.1.0
  flutter_native_splash: ^2.4.6
  flutter_offline: ^4.0.0
  flutter_screenutil: ^5.9.3
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.1.0
  gallery_saver: ^2.3.2
  gap: ^3.0.1
  google_sign_in: ^6.3.0
  googleapis_auth: ^2.0.0
  image_picker: ^1.1.2
  intl: any
  local_auth: ^2.3.0
  lottie: ^3.3.1
  modal_bottom_sheet: ^3.0.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  pub_semver: ^2.2.0
  restart_app: ^1.3.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  http: ^1.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/translations/
    - assets/svgs/
